### PR TITLE
:package: Update NuGet packages.

### PR DESCRIPTION
**Pull request by PureKrome**
REF: https://homelyau.atlassian.net/secure/RapidBoard.jspa?rapidView=3&projectKey=HDW&modal=detail&selectedIssue=HDW-2869&quickFilter=5

This is hopefully part of this card/requirmements.

some of the cli stuff i'm experimenting with require OpenApi v3. So this PR updates stuff to v3.

(side note: still not sure If i want to stick with Swashbuckle ... vs using NSwag).

### CODE REVIEW

**Comment by RPM1984** [comment]
any ideas why this drops coverage a whopping 13.6%?

**Comment by PureKrome** [comment]
Nope. No idea. I'll give it a quick look.

**Review by sergeimuravev — APPROVED** [review]

**Comment by PureKrome** [comment]
```
Calculating coverage result...
  Generating report 'C:\Projects\Work\Homely\Homely.AspNetCore.Mvc.Helpers\tests\Homely.AspNetCore.Mvc.Helpers.Tests\coverage.json'

+-------------------------------+--------+--------+--------+
| Module                        | Line   | Branch | Method |
+-------------------------------+--------+--------+--------+
| Homely.AspNetCore.Mvc.Helpers | 86.46% | 57.14% | 100%   |
+-------------------------------+--------+--------+--------+
| TestWebApplication            | 81.09% | 55.55% | 73.07% |
+-------------------------------+--------+--------+--------+

+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 83.5%  | 56.52% | 82.5%  |
+---------+--------+--------+--------+
| Average | 83.77% | 56.34% | 86.53% |
+---------+--------+--------+--------+
```

**Comment by PureKrome** [comment]
image

image

**Comment by PureKrome** [comment]
So if i can read this correctly, using a DIFFERENT TOOL (called coverlet) it's showing `83.5%` coverage.

The _other_ tool is showing `77.66%` coverage. Time to try the other tool, locally.

**Comment by RPM1984** [comment]
Code coverage problems everywhere 😞 .. we still haven't solved the issue in Homely.Listings either.. 😞 (even if thats codecov and not coverlet, etc).

**Comment by PureKrome** [comment]
@RPM1984 @sergeimuravev updated code again. Mainly:

- CI to use a matrix + specific testing patterns. (something i've wanted to try for a while. small repo, gave it a go finally)
- coverlet (.net core xplat) for code cov. it's _default_ with xunit projects since .. er ... .NET core 3+ ? (instead of the previous tool we were using).

**Review by RPM1984 — APPROVED** [review]
Coverage/CI updates should have probably been a seperate PR, but ok in this case given the convo (even though it seems the issue was there even before this PR)

**Comment by PureKrome** [comment]
@RPM1984 and @sergeimuravev  - I've removed the appveyor changes and moved them over to #25

**Comment by PureKrome** [comment]
all good to re-review.

**Review by RPM1984 — APPROVED** [review]

**Review by sergeimuravev — APPROVED** [review]

**Comment by sergeimuravev** [comment]
@RPM1984 Pls merge as I have no rights.

**Pull request merged**
